[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "zview"
version = "0.1.0"
description = "Multi-resolution Zarr viewer (PyQt5 + pyqtgraph, optional VisPy 3D)"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "pyqt5",
    "pyqtgraph",
    "PyOpenGL",
    "PyOpenGL_accelerate",
    "vispy",
]

[project.scripts]
zview = "zview.zview2:main"

[tool.setuptools.packages.find]
include = ["zview*"]
exclude = ["zview.__pycache__*"]
